### ISSUE TITLE
Doesn't work when vscode installed in read-only location

### ISSUE THREAD

**Issue by CertainLach** [shalldie/vscode-background#161]
When installed on nixos, fails to apply with the following error:
```
Error: EACCES: permission denied, open '/nix/store/i814rx33ab7pmrl0d4fhajxr2986wm5i-vscode-1.35.1/lib/vscode/resources/app/out/vs/workbench/workbench.main.css'
	at Object.fs.openSync (fs.js:577:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.writeFileSync (fs.js:1321:33)
	at Background.saveCssContent (/home/lach/.vscode/extensions/shalldie.background-1.1.19/out/background.js:69:12)
	at Background.install (/home/lach/.vscode/extensions/shalldie.background-1.1.19/out/background.js:169:14)
```
/nix/store is mounted as read-only, what about adding ability to change background without editing vscode resources?

**Comment by shalldie** [comment]
Here's the reason : https://github.com/shalldie/vscode-background#warns-%E8%AD%A6%E5%91%8A

By now, there's no way to change background's image but edit the css file.
I'm looking for a welcome way to do it, if a better way has been found, i'll try it. :D
