### ISSUE TITLE
这么久了  还是不好使么  mac 直接就是无效

### ISSUE THREAD

**Issue by lsxu** [shalldie/vscode-background#176]

**Comment by shalldie** [comment]
... mac 一直可以啊，从插件做出来到现在就一直可以用。

你有什么问题吗？

**Comment by lsxu** [comment]
#142 和这个一样

**Comment by lsxu** [comment]
最后实在是没办法了 按那个兄弟强改的方案搞的

**Comment by ycxalyn** [comment]
我这边也是不行，报这个错，帮忙看下呢
[renderer1] [error] Cannot set property 'dataProvider' of undefined: TypeError: Cannot set property 'dataProvider' of undefined
    at t.$registerTreeViewDataProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2819:386)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2824:474)
    at e._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2824:192)
    at e._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2823:301)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2823:70)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2822:139
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2824:1008
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:218)
    at Socket.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:288:459)
    at emitOne (events.js:96:13)

**Comment by ycxalyn** [comment]
主要是插件默认自带的那个图我也没有显示出来，按照其他issue说的加读写权限也还是一样没有任何效果

**Comment by shalldie** [comment]
@ycxalyn 你这个似乎是其他插件的报错信息

**Comment by shalldie** [comment]
@lsxu vscode下载后，最好不要就放在【下载目录】，可以放在【应用程序】，或者其他自定义目录下。

至于显示vscode的运行目录在 `private/var/folders....` 这个的情况暂不得知。

**Comment by s15723** [comment]
> @lsxu vscode下载后，最好不要就放在【下载目录】，可以放在【应用程序】，或者其他自定义目录下。
> 
> 至于显示vscode的运行目录在 `private/var/folders....` 这个的情况暂不得知。

> 得救了。。。之前vscode插件装了一堆没用的，重装vscode后放在下载目录里配置这个插件一直不生效

**Comment by 413476019** [comment]
> @lsxu vscode下载后，最好不要就放在【下载目录】，可以放在【应用程序】，或者其他自定义目录下。
> 
> 至于显示vscode的运行目录在 `private/var/folders....` 这个的情况暂不得知。

牛，研究了好久一直都不行，结果按你说的这个方法就好了
